import { useEffect, useState } from 'react';
import { AlertTriangle, ClipboardCheck, CloudUpload, ThermometerSun, ShieldCheck, ArrowUpRight, Radio, MapPin } from 'lucide-react';
import type { View } from '@/types';
interface Props { navigate: (v: View) => void; queueCount: number; shiftStart: number; online: boolean; siteName: string; gpsText: string; }
const actions = [
  { view: 'inspection', title: 'START PRE-SHIFT INSPECTION', subtitle: 'Verify site readiness', icon: ClipboardCheck, number: '01' },
  { view: 'queue', title: 'SYNC QUEUE', subtitle: 'Review offline reports', icon: CloudUpload, number: '02' },
  { view: 'heat', title: 'WORKER HEAT CHECK-IN', subtitle: 'Log thermal condition', icon: ThermometerSun, number: '03' },
  { view: 'supervisor', title: 'SUPERVISOR DASHBOARD', subtitle: 'Incidents & dispatch', icon: ShieldCheck, number: '04' },
] as const;
export default function CommandCenter({ navigate, queueCount, shiftStart, online, siteName, gpsText }: Props) {
  const [now, setNow] = useState(Date.now());
  useEffect(() => { const id = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(id); }, []);
  const elapsed = Math.max(0, Math.floor((now - shiftStart) / 1000));
  const timer = `${String(Math.floor(elapsed / 3600)).padStart(2, '0')}:${String(Math.floor(elapsed % 3600 / 60)).padStart(2, '0')}:${String(elapsed % 60).padStart(2, '0')}`;
  return <div className="space-y-7">
    <div className="flex items-end justify-between gap-4 flex-wrap"><div><p className="eyebrow">OPERATIONS / COMMAND CENTER</p><h1 className="text-3xl md:text-5xl font-black tracking-tight mt-2 text-white sun:text-yellow-400">FIELD OPERATIONS<span className="text-amber-400">.</span></h1><p className="text-zinc-400 mt-3 sun:text-yellow-400">Safety systems active. Every second counts.</p></div><div className="text-xs tracking-widest font-bold text-amber-400 border border-amber-400/40 px-4 py-2">● SHIFT IN PROGRESS</div></div>
    <section className="panel relative overflow-hidden"><div className="absolute right-0 top-0 bottom-0 w-1/3 opacity-20 solar-grid pointer-events-none"/><div className="relative grid md:grid-cols-[1fr_auto] gap-7 p-6 md:p-8"><div><p className="eyebrow">ACTIVE SECTOR / LIVE</p><h2 className="text-2xl md:text-3xl font-bold text-white sun:text-yellow-400 mt-3 break-words">{siteName}</h2><p className="text-zinc-400 text-sm mt-2 sun:text-yellow-400 flex items-center gap-2"><Radio size={14} className="text-amber-400 shrink-0"/> Field team operational · {online ? 'Network connected' : 'Offline capture active'}</p><p className="text-zinc-400 text-sm mt-1 sun:text-yellow-400 flex items-center gap-2 font-mono"><MapPin size={14} className="text-amber-400 shrink-0"/> {gpsText}</p><button onClick={() => navigate('location')} className="mt-4 text-xs font-bold tracking-wider text-amber-400 hover:text-yellow-300 sun:text-yellow-400">EDIT LOCATION SETUP →</button></div><div className="md:border-l border-zinc-700 md:pl-8"><p className="eyebrow">SHIFT ELAPSED</p><div className="font-mono text-3xl md:text-4xl font-bold tracking-tight text-amber-400 mt-3 tabular-nums">{timer}</div><p className="text-zinc-500 text-xs mt-2 sun:text-yellow-400">HH : MM : SS</p></div></div></section>
    <button onClick={() => navigate('hazard')} className="w-full min-h-40 md:min-h-48 bg-amber-400 text-slate-950 border-4 border-amber-200 hover:bg-yellow-300 transition-colors flex items-center justify-between p-6 md:p-10 text-left hazard-pulse sun:border-yellow-400 sun:bg-black sun:text-yellow-400"><div className="flex items-center gap-5"><div className="border-2 border-slate-950 sun:border-yellow-400 p-3 md:p-4"><AlertTriangle className="w-9 h-9 md:w-12 md:h-12" strokeWidth={2.5}/></div><div><span className="text-xs tracking-[.2em] font-black">PRIORITY ACTION / 00</span><div className="text-3xl md:text-5xl font-black tracking-tight mt-1">REPORT HAZARD</div><p className="font-medium mt-2 text-sm">Rapid field report · Works without signal</p></div></div><ArrowUpRight className="hidden sm:block w-8 h-8"/></button>
    <div><div className="flex justify-between items-center mb-4"><p className="eyebrow">FIELD TOOLS / QUICK ACCESS</p><p className="text-xs text-zinc-500 sun:text-yellow-400">SELECT AN OPERATION ↓</p></div><div className="grid sm:grid-cols-2 gap-3">{actions.map(({ view, title, subtitle, icon: Icon, number }) => <button key={view} onClick={() => navigate(view)} className="panel text-left p-5 md:p-6 hover:border-amber-400 transition-colors group min-h-36 flex flex-col justify-between"><div className="flex justify-between items-start"><Icon className="text-amber-400" size={27}/><span className="font-mono text-xs text-zinc-500 sun:text-yellow-400">/{number}</span></div><div className="flex justify-between items-end gap-2"><div><div className="text-white sun:text-yellow-400 font-bold tracking-wide text-sm md:text-base">{title} {view === 'queue' && <span className="bg-amber-400 text-slate-950 px-2 py-0.5 ml-1 text-xs">{queueCount}</span>}</div><div className="text-zinc-400 sun:text-yellow-400 text-xs mt-1">{subtitle}</div></div><ArrowUpRight size={18} className="text-zinc-500 group-hover:text-amber-400 sun:text-yellow-400"/></div></button>)}</div></div>
  </div>;
}
