import { X, Truck, CheckCircle2, MapPin } from 'lucide-react';
import type { SupervisorIncident } from '@/types';
import { mapsUrl } from '@/hooks/useGeolocation';
import { Image } from '@/components/ui/image';
import { useEffect, useState } from 'react';
interface Props { incident: SupervisorIncident; onClose: () => void; onDispatch: (crew: string) => Promise<void>; onResolve: () => Promise<void>; }
export default function IncidentDetail({ incident, onClose, onDispatch, onResolve }: Props) {
  const [crew, setCrew] = useState(incident.assignedCrew);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => { const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [onClose]);
  async function act(action: () => Promise<void>) { setBusy(true); setError(''); try { await action(); } catch (err) { setError(err instanceof Error ? err.message : 'Action failed.'); } finally { setBusy(false); } }
  return <div className="fixed inset-0 z-50 bg-black/80 flex items-center justify-center p-3 md:p-6" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><section role="dialog" aria-modal="true" aria-label="Incident details" className="panel w-full max-w-xl max-h-[90vh] overflow-y-auto p-5 md:p-8 shadow-2xl"><div className="flex justify-between items-start gap-4"><div><p className="eyebrow">INCIDENT / {incident.id.slice(0, 8)}</p><h2 className="text-2xl font-black mt-2">{incident.isSos ? 'EMERGENCY SOS' : incident.type} <span className="text-amber-400">/ {incident.severity}</span></h2></div><button aria-label="Close details" onClick={onClose} className="p-2 border border-zinc-600 sun:border-yellow-400"><X/></button></div><div className="grid grid-cols-2 gap-4 mt-6 text-sm"><div><p className="eyebrow">LOCATION</p><p className="mt-1 break-words">{incident.location}</p>{incident.latitude != null && incident.longitude != null && <a href={mapsUrl(incident.latitude, incident.longitude)} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-xs font-bold text-amber-400 hover:text-yellow-300 sun:text-yellow-400"><MapPin size={14}/> OPEN IN GOOGLE MAPS ↗</a>}</div><div><p className="eyebrow">REPORTED</p><p className="mt-1">{new Date(incident.timestamp).toLocaleString()}</p></div><div><p className="eyebrow">ASSIGNED CREW</p><p className="mt-1">{incident.assignedCrew || 'Unassigned'}</p></div><div><p className="eyebrow">STATUS</p><p className="mt-1">{incident.resolved ? 'RESOLVED' : 'OPEN'}</p></div></div><div className="border-t border-zinc-700 mt-6 pt-5"><p className="eyebrow">FIELD NOTES</p><p className="mt-2 whitespace-pre-wrap break-words">{incident.notes || 'No additional notes.'}</p></div>{incident.photoUrl && !incident.photoUrl.startsWith('local-photo:') && <Image src={incident.photoUrl} alt="Incident snapshot" className="w-full h-48 object-cover mt-5"/>}<div className="border-t border-zinc-700 mt-6 pt-5 space-y-3"><label className="eyebrow block" htmlFor="crew-name">ASSIGN RESPONSE CREW</label><div className="flex gap-2"><input id="crew-name" className="field-input flex-1 min-w-0" value={crew} onChange={e => setCrew(e.target.value)} placeholder="Crew name or team ID"/><button className="action-button flex items-center gap-2" disabled={busy || !crew.trim() || incident.resolved} onClick={() => act(() => onDispatch(crew.trim()))}><Truck size={17}/> DISPATCH CREW</button></div><button className="secondary-button flex items-center justify-center gap-2 w-full" disabled={busy || incident.resolved} onClick={() => act(onResolve)}><CheckCircle2 size={17}/>{incident.resolved ? 'INCIDENT RESOLVED' : 'MARK RESOLVED'}</button>{error && <p role="alert" className="text-red-400">{error}</p>}</div></section></div>;
}
