import { useState, type FormEvent } from 'react';
import { ClipboardCheck, ListChecks } from 'lucide-react';
import type { Checkpoint, InspectionResult } from '@/types';
interface Props { onSave: (results: InspectionResult[]) => Promise<void>; online: boolean; siteName: string; checkpoints: Checkpoint[]; }
export default function InspectionFlow({ onSave, online, siteName, checkpoints }: Props) {
  const [values, setValues] = useState<Record<string, boolean>>({});
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [done, setDone] = useState(false);
  const checked = checkpoints.filter(c => values[c.id]).length;
  const complete = checkpoints.length > 0 && checked === checkpoints.length;
  async function submit(e: FormEvent) { e.preventDefault(); if (!complete) return; setSaving(true); setError(''); try { await onSave(checkpoints.map(c => ({ ...c, passed: !!values[c.id] }))); setDone(true); } catch (err) { setError(err instanceof Error ? err.message : 'Could not save inspection.'); } finally { setSaving(false); } }
  return <div className="max-w-2xl mx-auto space-y-6"><div><p className="eyebrow">FIELD PROTOCOL / PRE-SHIFT</p><h1 className="page-title">Pre-shift inspection</h1><p className="text-zinc-400 sun:text-yellow-400 mt-2">{siteName}</p></div>{done ? <div className="panel p-8 text-center"><ClipboardCheck className="mx-auto text-emerald-400 sun:text-yellow-400 mb-4" size={44}/><h2 className="text-2xl font-bold">Inspection recorded</h2><p className="text-zinc-400 sun:text-yellow-400 mt-2">Your site readiness check is saved.</p><button type="button" className="secondary-button mt-6" onClick={() => { setValues({}); setDone(false); }}>START NEW INSPECTION</button></div> : !checkpoints.length ? <div className="panel p-10 text-center"><ListChecks className="mx-auto text-amber-400 mb-4" size={40}/><h2 className="text-xl font-bold">No checkpoints set up</h2><p className="text-zinc-400 sun:text-yellow-400 mt-2">A supervisor can add inspection checkpoints in <b>Supervisor → Inspection checkpoints</b>.</p></div> : <form onSubmit={submit} className="panel p-6 space-y-5"><div className="flex justify-between items-center gap-3"><p className="eyebrow">VERIFY ALL CHECKPOINTS</p><p className="font-mono text-xs text-zinc-400 sun:text-yellow-400">{checked}/{checkpoints.length}</p></div>{checkpoints.map((c, i) => <label key={c.id} className="flex items-center gap-4 border border-zinc-700 p-4 cursor-pointer hover:border-amber-400 sun:border-yellow-400"><input type="checkbox" className="w-6 h-6 shrink-0 accent-amber-400" checked={!!values[c.id]} onChange={e => setValues(v => ({ ...v, [c.id]: e.target.checked }))}/><span className="font-medium break-words min-w-0"><span className="text-amber-400 font-mono mr-3">{String(i + 1).padStart(2, '0')}</span>{c.label}</span></label>)}{!online && <p className="text-amber-400 text-sm">Connect to a network to submit an inspection. Hazard reports and SOS still save offline.</p>}{error && <p role="alert" className="text-red-400">{error}</p>}<button className="action-button w-full" disabled={saving || !online || !complete}>{saving ? 'RECORDING INSPECTION…' : complete ? 'SUBMIT INSPECTION' : `VERIFY ALL CHECKPOINTS (${checked}/${checkpoints.length})`}</button></form>}</div>;
}
