import { useState } from 'react';
import type { SupervisorIncident, Severity } from '@/types';
import IncidentDetail from '@/components/IncidentDetail';
import { Activity, AlertTriangle, ClipboardCheck, CloudOff, LogOut } from 'lucide-react';
interface Props { incidents: SupervisorIncident[]; inspections: number; pending: number; loading: boolean; online: boolean; onUpdate: (incident: SupervisorIncident, patch: { assigned_crew?: string; resolved?: boolean }) => Promise<void>; onSignOut: () => void; }
export default function SupervisorDashboard({ incidents, inspections, pending, loading, online, onUpdate, onSignOut }: Props) {
  const [filter, setFilter] = useState<Severity | 'ALL'>('ALL');
  const [selected, setSelected] = useState<SupervisorIncident | null>(null);
  const visible = incidents.filter(r => filter === 'ALL' || r.severity === filter).sort((a, b) => b.timestamp.localeCompare(a.timestamp));
  const metrics = [{ label: 'TOTAL INSPECTIONS', value: inspections, icon: ClipboardCheck }, { label: 'OPEN HAZARDS', value: incidents.filter(i => !i.resolved).length, icon: Activity }, { label: 'CRITICAL INCIDENTS', value: incidents.filter(i => !i.resolved && i.severity === 'CRITICAL').length, icon: AlertTriangle }, { label: 'PENDING SYNCS', value: pending, icon: CloudOff }];
  async function update(patch: { assigned_crew?: string; resolved?: boolean }) { if (!selected) return; await onUpdate(selected, patch); setSelected(s => s ? { ...s, assignedCrew: patch.assigned_crew ?? s.assignedCrew, resolved: patch.resolved ?? s.resolved } : null); }
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">SUPERVISOR / COMMAND OVERVIEW</p><h1 className="page-title">Incident command</h1><p className="text-zinc-400 sun:text-yellow-400 mt-2">{online ? 'Live synchronized incident stream' : 'Offline — displaying last loaded incidents and local reports'}</p></div><button onClick={onSignOut} className="secondary-button flex items-center gap-2"><LogOut size={17}/> SIGN OUT</button></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{metrics.map(({ label, value, icon: Icon }) => <div key={label} className="panel p-5"><div className="flex justify-between"><p className="eyebrow text-[10px]">{label}</p><Icon size={18} className="text-amber-400"/></div><div className="text-3xl md:text-4xl font-black mt-5 text-white sun:text-yellow-400">{value.toString().padStart(2, '0')}</div></div>)}</div><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Live incident stream</h2><p className="text-xs text-zinc-400 sun:text-yellow-400 mt-1">Select a row to review and respond</p></div><label className="text-xs font-bold text-zinc-400 sun:text-yellow-400">SEVERITY <select aria-label="Filter severity" className="field-input ml-2" value={filter} onChange={e => setFilter(e.target.value as Severity | 'ALL')}><option value="ALL">ALL</option>{['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'].map(x => <option key={x}>{x}</option>)}</select></label></div>{loading ? <div className="panel p-12 text-center">Loading incidents…</div> : visible.length ? <div className="space-y-2">{visible.map(i => <button key={i.id} onClick={() => setSelected(i)} className="panel w-full p-4 md:p-5 text-left hover:border-amber-400 transition-colors grid grid-cols-[1fr_auto] md:grid-cols-[1.2fr_1fr_1fr_auto] gap-3 items-center"><div><p className="font-bold text-white sun:text-yellow-400">{i.isSos ? 'EMERGENCY SOS' : i.type}</p><p className="text-xs text-zinc-400 sun:text-yellow-400 mt-1">{i.id.slice(0, 8)} · {new Date(i.timestamp).toLocaleString()}</p></div><span className="text-sm text-zinc-300 sun:text-yellow-400 hidden md:block truncate">{i.location}</span><span className={`font-bold text-xs ${i.severity === 'CRITICAL' ? 'text-red-400' : 'text-amber-400'} sun:text-yellow-400`}>{i.severity}</span><span className={`text-xs font-bold border px-2 py-1 ${i.resolved ? 'text-emerald-400 border-emerald-500' : 'text-amber-400 border-amber-400'} sun:text-yellow-400 sun:border-yellow-400`}>{i.resolved ? 'RESOLVED' : 'OPEN'} →</span></button>)}</div> : <div className="panel p-12 text-center text-zinc-400 sun:text-yellow-400">{filter === 'ALL' ? 'No incidents reported yet.' : `No ${filter.toLowerCase()} incidents.`}</div>}{selected && <IncidentDetail incident={selected} onClose={() => setSelected(null)} onDispatch={crew => update({ assigned_crew: crew })} onResolve={() => update({ resolved: true })}/>}</div>;
}
